#! /bin/sh
#
# hypview - Wrapper script for the hyperviewer application.
#
# Copyright (c) 2004 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

# Optionally use shared libs under the local directory.
if [ -d libs ]; then
    if [ $LD_LIBRARY_PATH ]; then
        LD_LIBRARY_PATH=./libs:$LD_LIBRARY_PATH
    else
        LD_LIBRARY_PATH=./libs
    fi
    export LD_LIBRARY_PATH
fi

# Optionally use Pango loadable modules under the local directory.
if [ -d libs/pango ]; then
    PANGO_RC_FILE=./pangorc.local; export PANGO_RC_FILE
fi

# If the wxPython or OpenGL directories are local, they will be used.
python hypview.py $*
