#! /usr/bin/awk -f
#
# Copyright (c) 2006 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

BEGIN {
	printf("timeval unsigned\n");
	printf("title\n");
	printf("Event Timeline\n");
	printf("xlabel\n");
	printf("time\n");
	printf("ylabel\n");
	printf("agent\n");
	printf("white\n");

	firsttime = 0;
	agents = 0;
}

/Agent: / {
	agents += 1;
	agent[$2] = agents;
}

/Fire: / {
	split($3, tv, /:/);
	split($5, aname, /:/);

	if (firsttime == 0 || tv[2] < firsttime)
		firsttime = tv[2];
	if (aname[2] in agent) {
		printf("x %s.%s %s\n", tv[2], tv[3], agent[aname[2]]);
	}
}

END {
	for (ag in agent) {
		printf("rtext %s.0 %d\n%s\n", firsttime - 5, agent[ag], ag);
	}
	printf("go\n");
}
