#!/usr/bin/perl

#
# Copyright (c) 2009 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

require common;

use strict;

#
# Run all tests specified in a testfile
#

#
# Read config from file passed on command line
#
die "Usage: $0 <testfile>" unless @ARGV==1;
my ($testfile) = @ARGV;
readtestfile($testfile);

#
# Set up global vars that store directory locations, etc.
#
setglobals();

#
# Make intermediate directories
#
if (-d $::testdir) {
    print "Clearing out old testdir\n";
    system "rm -rf $::testdir";
}

foreach my $dir ($::testdir, $::outdir, $::statdir) {
    mkdir $dir or die "Unable to make $dir: $!";
}

#
# Actually run assign
#
foreach my $test (enumeratetests()) {
    my $cmdline = "$CFG::assignbin $CFG::assignopts " . ptopfile($test) .
                                             " " . topfile($test);
    my $logfile = logfile($test);
    print "Running $test ... ";
    my $oldtime = time();
    my $rv = system "$cmdline > $logfile 2>&1";
    my $newtime = time();
    my $delta = $newtime - $oldtime;
    print "($delta seconds)\n";
    if ($rv) {
        print "Failed!\n";
        system "touch " . failedfile($test);
    } else {
        system "touch " . passedfile($test);
    }
}
