#
# Copyright (c) 2006 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

EXECUTABLE=UdpClient
CC=g++ -g
CFLAGS=

COMPILE_DIR=.OBJECTS

OBJECTS=${COMPILE_DIR}/UdpClient.o \
	${COMPILE_DIR}/UdpPacketSensor.o \
	${COMPILE_DIR}/UdpMinDelaySensor.o \
	${COMPILE_DIR}/UdpMaxDelaySensor.o \
	${COMPILE_DIR}/UdpThroughputSensor.o \
	${COMPILE_DIR}/UdpPacketInfo.o \
	${COMPILE_DIR}/UdpSensor.o \
	${COMPILE_DIR}/UdpSensorList.o \
	${COMPILE_DIR}/UdpRttSensor.o \
	${COMPILE_DIR}/UdpLossSensor.o \
	${COMPILE_DIR}/UdpAvgThroughputSensor.o 


COMMON_INCLUDES=UdpLibs.h \
		UdpState.h

${EXECUTABLE}: ${OBJECTS} 
	${CC} -o $@ ${CFLAGS} $+ -lpcap

${COMPILE_DIR}/UdpClient.o: UdpClient.cc UdpPacketSensor.h ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpAvgThroughputSensor.o: UdpAvgThroughputSensor.cc UdpAvgThroughputSensor.h ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpLossSensor.o: UdpLossSensor.cc UdpLossSensor.h ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpRttSensor.o: UdpRttSensor.cc UdpRttSensor.h ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpMinDelaySensor.o: UdpMinDelaySensor.cc UdpMinDelaySensor.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpMaxDelaySensor.o: UdpMaxDelaySensor.cc UdpMaxDelaySensor.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpThroughputSensor.o: UdpThroughputSensor.cc UdpThroughputSensor.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpPacketSensor.o: UdpPacketSensor.cc UdpPacketSensor.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpPacketInfo.o: UdpPacketInfo.cc UdpPacketInfo.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpSensor.o: UdpSensor.cc UdpSensor.h ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpSensorList.o: UdpSensorList.cc UdpSensorList.h ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

clean:
	rm -f ${COMPILE_DIR}/*.o ${EXECUTABLE}

