#!/bin/sh

#
# A little script to put the testbed ports into the ports tree
#

PORTSDIR=${PORTSDIR:-/usr/ports}
PORTSUBDIR=misc
SRCDIR=`dirname $0`
PORTS="emulab-boss emulab-fs emulab-ops emulab-tftp-hpa net-snmp4 p5-GD-old p5-DBD-mysql50-old ulsshxmlrpcpp emulab-iperf emulab-php4 emulab-php5 emulab-py-m2crypto emulab-py-m2crypto-noegg emulab-mailman emulab-pubsub emulab-extras emulab-clrhouse emulab-protogeni p5-IO-EventMux p5-IO-EventMux-Socket-MsgHdr p5-Privileges-Drop p5-RPC-Async p5-SNMP libtelnet emulab-dhcp31-client emulab-tipserv"

#EPORTS="elvind libelvin emulab-pubsub-elvincompat"
#EPATCH=ports-elvin.patch

echo "Copying ports ..."
for PORT in $PORTS
do
    cp -r $SRCDIR/$PORT $PORTSDIR/$PORTSUBDIR
    if [ "$?" != "0" ]
    then
	exit 1
    fi
done

# "register" the emulab ports
echo "Patching $PORTSDIR/$PORTSUBDIR/Makefile ..."
patch -p0 $PORTSDIR/$PORTSUBDIR/Makefile ports.patch

## recreate the index
#echo "Recreating ports INDEX (this will take forever) ..."
#cd $PORTSDIR
#make index

echo "Done!"
exit 0
