#!/usr/bin/perl -w

#
# Copyright (c) 2000-2002 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#


# This scripts takes a DB and a select statement and dumps the
# results of the table in a format that can easily be inserted into
# atest script for use with tb_compare.

use DBI;

if ($#ARGV != 1) {
    print STDERR "Syntax: $0 <db> <query>\n";
    exit(1);
}

($db,$query) = @ARGV;

$dbh = DBI->connect("DBI:mysql:database=$db;host=localhost") || 
	die "Could not connect to DB.\n";
$sth = $dbh->prepare($query);
$sth->execute;

print "\@result = (\n";
while (@row = $sth->fetchrow_array) {
    print "[\"" . $row[0] . "\"";
    foreach $element (@row[1..$#row]) {
	print ",\"$element\""
    }
    print "\],\n";
}
print ");\n";
