#!/bin/sh
### BEGIN INIT INFO
# Provides:          topd
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Remote top daemon
# Description:       Remote top daemon
### END INIT INFO

. /lib/init/vars.sh
. /lib/lsb/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/etc/emulab
DESC="Remote top daemon"

PIDFILE=/var/run/topd.pid
ROLE=$(cat /var/emulab/boot/role)

topd_start()
{
	if [ $ROLE != "sharedhost" ]; then
		return 0
	fi
	
	log_progress_msg "topd"

	topd
	
	return $?
}

topd_stop()
{
	if [ $ROLE != "sharedhost" ]; then
		return 0
	fi

	log_progress_msg "topd"
	
	kill $(cat $PIDFILE)
	
	return $?
}

topd_restart()
{
	if [ $ROLE != "sharedhost" ]; then
		return 0
	fi

	log_progress_msg "topd"
	
	kill $(cat $PIDFILE)

	topd
	
	return 0
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC"
	topd_start
	log_end_msg 0
	;;
  stop)
	log_daemon_msg "Stopping $DESC"
	topd_stop
	log_end_msg $ret
	;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC"
	topd_restart
	log_end_msg $ret
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

exit 0
