PORTNAME=	IO-EventMux-Socket-MsgHdr
PORTVERSION=	0.02
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sklower@berkeley.edu
COMMENT=	sendmsg, recvmsg and ancillary data in Perl5

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	modbuild

MAN3=		IO::EventMux::Socket::MsgHdr.3

.include <bsd.port.mk>
