#!/bin/sh

mkdir -p /var/lock/subsys
echo -n 'testbed config: '
/usr/local/etc/emulab/rc/rc.testbed
if [ ! $? -eq 0 ]; then
    echo "Failed to start /usr/local/etc/emulab/rc/rc.testbed: $?"
    #sv down testbed
    exit $?
fi
touch /var/lock/subsys/testbed

#
# runit expects the run file to continue execution until death.
#
while [ 1 -eq 1 ]; do
    sleep 60
done

exit 0
