#!/usr/bin/perl

#
# Copyright (c) 2000-2002 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#


# This program takes a list of machines and removes all the VLANs
# whose every member is an argument.

#debug
my $d = 0;

#
# Configure variables
#
my $TB	= "/users/mshobana/CloudLabonESI/emulab-devel-new/emulab-devel/sample_build";

$snmpit = "$TB/bin/snmpit";

if ($#ARGV < 0) {
  die "Syntax: $0 <node> [<node>] ...\n";
}
open(SNMPIT,"$snmpit -l |") || die "Error running $snmpit -l\n";

%machines = ();

while ($#ARGV >= 0) {
  $node = pop(@ARGV);
  print "Found node $node\n" if $d;
  $machines{$node} = "";
}

print "Resetting VLANs for: ",join(" ",keys %machines),"\n";

@toremove = ();

while (<SNMPIT>) {
  chop;
  @line = split;
  $id = $line[0];
  if (! ($id =~ /[0-9]+/)) {
    next;
  }
  if ($id == 1) {
    next;
  }
  # Skip VLANs with no members, which tries to delete VLAN 1,
  # as well as private VLANs
  if (@line < 2) {
    next;
  }
  $remove = 1;
  foreach $member (@line[2..$#line]) {
    @elements = split(":",$member);
    if (! defined($machines{$elements[0]})) {
      $remove = 0;
      last;
    }
  }
  if ($remove == 1) {
    push(@toremove,$id);
  }
}

close(SNMPIT);

$vlans = join(" ",@toremove);
print "Removing VLANs: $vlans\n";

my @success=();
my @fail=();
my $error = 0;

if (@toremove > 0) {
  #system("$snmpit -u -r $toremove");
  open(RM,"$snmpit -r $vlans 2>&1 |") ||
    die "Error running $snmpit -r $toremove\n";
  while(<RM>) {
    print "snmpit:$_" if $d;
    chop;
    if ( /^[ \t]*$/ ) { next; }
    if ( /Removing VLAN \#(\d+) ... (.*)/ ) {
      my $num = $1;
      my $result = $2;
      if ( $result =~ /Succeeded/) {
	push(@success,$num);
      } else {
	print "$_\n";
	if (<RM>) { print "$_\n"; }
	push(@fail,$num);
	$error++;
      }
    } else {
      print "$_\n";
      $error++;
    }
  }
  close(RM);
}

if ($error || @fail ) {
  print "VLAN removal had $error error(s).\n";
  print "Removal failed for VLANs: @fail\n";
  print "Removal succeeded for VLANs: @success\n";
} else {
  print "Removal succeeded for VLANs: @success\n";
}

$error;
