#!/usr/bin/perl -w

#
# Copyright (c) 2010 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

use English;
use strict;

#
# Configure variables
#
my $TB			= "/users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish";

#
# Turn off line buffering on output
#
$| = 1;

#
# Untaint the path
# 
$ENV{'PATH'} = "$TB/bin:$TB/sbin:/bin:/usr/bin:/sbin:/usr/sbin";
delete @ENV{'IFS', 'CDPATH', 'ENV', 'BASH_ENV'};

#
# Testbed Support libraries
#
use lib "/users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/lib";
use libdb;
use libtestbed;

#
# Handle command-line options.
#
sub usage() {
    print STDERR "Usage: $0 <owner-uid> <filename>\n";
    exit( 1 );
}

usage() unless @ARGV == 2;
my ( $uid, $filename ) = @ARGV;
#
# Must taint check!
#
if ($uid =~ /^([-\w #%&*+,.\/:;=?@\[\\\]^{|}]+)$/) {
    $uid = $1;
}
else {
    print STDERR "Bad character in uid\n";
    exit( 1 );
}

if ($filename =~ /^([-\w #%&*+,.\/:;=?@\[\\\]^{|}]+)$/) {
    $filename = $1;
}
else {
    print STDERR "Bad character in filename\n";
    exit( 1 );
}

# We could use MySQL's UUID() function, but if we call it in the INSERT it
# becomes a pain to retrieve it.  So we do the job ourselves.
my $uuid = `/usr/bin/uuidgen`;
chomp $uuid;

my $result = DBQueryWarn( "INSERT INTO blobs SET uuid='$uuid', " .
			  "filename='$filename', owner_uid='$uid';" );
unless( $result ) {
    print STDERR "Could not insert record.\n";
    exit( 1 );
}

print "$uuid\n";

exit( 0 );
