#!/bin/sh
#
# Copyright (c) 2008 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/auth.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/emotes.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/exclasses.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/exp-intro.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/exp-swapping.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/hw-recommend.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/jail.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/linkdelays.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/linktest.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/netbuilddoc.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/pc2000.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/pc3000.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/plab.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/doc/windows.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/groups.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/hardware-emulab.net.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/hardware.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/otheremulabs.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/policies.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/rdp-mime.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/security.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/software.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/ssh-mime.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/swapping.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/abcd.png
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/advanced.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/behindthescenes.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/control-net.png
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/dumbell.png
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/elabinelab-pic1.png
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/elabinelab.php3
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/eventsystem.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/firewall-experiment.png
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/firewall.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/gnuradio.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/ixp.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/netfpga.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/nscommands.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/nse.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_back.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_back_detail.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_back_detail_thumb.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_back_marked.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_back_marked_thumb.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_back_thumb.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_front_left.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_front_left_thumb.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_front_right.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/pc600wifi_front_right_thumb.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/routing.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/routing.png
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/secure.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/shark_howto.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/simple.jpg
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/tutorial.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/tutorial.php3
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/vnodes-list.png
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/vnodes.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/widearea.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/tutorial/wireless.html
rm -f /users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/www/widearea.html
