#!/usr/local/bin/python
# -*- python -*-
#
# Copyright (c) 2000-2003 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

import sys
sys.path.append("/users/achauhan/Cloudlab/CloudLabonESI/emulab-devel-new/emulab-devel/build_aish/lib")
from libtestbed import *
import libplab
import getopt

RENEW_PERIOD = 6*60*60  # every six hours

def usage(me):
    print "Usage: %s [ -vd ]" % me
    sys.exit(1)
    return # NOTREACHED

def main(args):
    me = args[0]


    parser = TBParser()
    opts, args = parser.parse_args(args[1:])

    libplab.debug = opts.debug
    libplab.verbose = opts.verbose
    
    plab = libplab.Plab()
    daemon = pydaemon(pydaemon.SYSLOG)

    if not parser.values.debug:
        daemon.daemonize()
        pass
    
    daemon.daemonLoop(plab.renew, RENEW_PERIOD)

    return # NOTREACHED

if __name__ == "__main__":
    main(sys.argv)

