#!/usr/bin/perl -w
#
# Copyright (c) 2000-2012, 2017 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#
# Set the version and build info into the DB, at a toplevel install.
#
use English;
use Getopt::Std;
use POSIX qw(strftime);

#
# Configure variables
#
my $DESTDIR   = "";
if (exists($ENV{"DESTDIR"})) {
    $DESTDIR = $ENV{"DESTDIR"};
}
my $SRCDIR    = "../..";
my $ETCEMULAB = "$DESTDIR/etc/emulab";
my $VERSION   = "$ETCEMULAB/version";
my $GITTHING  = "tools/git/current_branch_head";

#
# Use the upper level tool to get the git hash, unless we were configured
# as part of the full emulab tree, in which case SRCDIR is already at
# the top of the tree.
#
my $path = (-e "$SRCDIR/$GITTHING" ? $SRCDIR : "$SRCDIR/..");
my $hash = `cd $path; $GITTHING`;
if ($?) {
    print STDERR
	"*** $0:\n".
	"    Unable to get commit hash for source tree\n";
    exit(0);
}
else {
    chomp($hash);
}
print "Hash is $hash\n";
if (-e "$ETCEMULAB") {
    print "Writing to $VERSION\n";
    system("echo '$hash' > $VERSION");
    exit(1)
	if ($?);
}
exit(0);
