#!/usr/bin/perl -w
#
# Copyright (c) 2000-2002 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#
use English;

#
# Setup the files and environment required for NSE and start it
#
# usage: startnse &
# 

# Drag in path stuff so we can find emulab stuff.
BEGIN { require "/etc/emulab/paths.pm"; import emulabpaths; }

# Stuff is here now.
chdir $BINDIR;

$id = `id`;
($vnode,$eid,$pid) = split (/\./, `hostname`);
$logpath = "/proj/$pid/exp/$eid/logs/nse-$vnode.log";
umask(002);
open( STDOUT, ">>$logpath");
open( STDERR, ">>&STDOUT" );
if( $id =~ /uid=(\d+)/ ) {
    if( $1 ne "0" ) {
        system("sudo nse nseinput.tcl");
    } else {
        system("nse nseinput.tcl");
    }
}
