#!/usr/bin/perl
#
# Copyright (c) 2006 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

#
# cloudinfo-set <pid> <eid>: Set the cloud info based on an input file of the form:
#
#####################   <pid> <eid>
#   <src> <dst> <bw> <delay> <loss>
#
# Where <src> and <dst> or of the form "elab-*" for now.

use strict;

my $TEVC = "/usr/testbed/bin/tevc";

#local $_ = <>;
#chop;
#my ($pid,$eid) = /^(\S+)\s+(\S+)$/ or die
#  "First line must be of the form \"<pid> <eid>\"\n";
my $pid = $ARGV[0];
my $eid = $ARGV[1];

my $failures = 0;

while (<STDIN>) {
    my ($src, $dst, $bw, $del, $plr) = split /\s+/;
    my $dstip = $dst;
    if ($dstip !~ /^\d+\.\d+\.\d+\.\d+$/) {
	$dst =~ (/^elab-(\d+)$/) or die "Host names must be of the form elab-NUM\n";
	$dstip = "10.0.0.$1";
    }
    my $srcip = $src;
    if ($srcip =~ /^\d+\.\d+\.\d+\.(\d+)$/)
    {
	$src = "elab-$1";
    }
    my $cmd = "$TEVC -e $pid/$eid now elabc-$src MODIFY ".
      "DEST=$dstip BANDWIDTH=$bw DELAY=$del PLR=$plr";
    print STDERR "$cmd\n";
    system("$cmd");
    if ($? != 0) {
	print STDERR "*** Failed to set paramters for $src -> $dst\n";
	$failures++;
    }
}

exit $failures;
