#!/bin/sh
#
# Copyright (c) 2006 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

TEVC=/usr/testbed/bin/tevc

if [ $# != 2 ]; then
    echo "usage: $0 pid eid"
    exit 1
fi

pid=$1
eid=$2

echo "##### reinstalling tarballs and RPMs"
$TEVC -w -t 30 -e $pid/$eid now tfhosts run

echo "WARNING: you will still need to run start-experiment to restart"
echo "         stubs and monitors (if they have changed)."

exit $?
