#!/bin/sh
#
# Copyright (c) 2006, 2007 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

files="pelab/auto-pelab.ns pelab/common-env.sh pelab/init-elabnodes.pl pelab/run-sanity.sh pelab/dbmonitor pelab/libnetmon pelab/magent pelab/monitor pelab/pelabdb.pwd pelab/stub pelab/iperfd"

if [ $# != 1 ]; then
    echo "usage: $0 tarball-path"
    exit 1
fi

path=$1

if [ ! -d ../pelab ]; then
   echo "should be run from 'pelab' subdir"
   exit 1
fi

echo "##### cleaning up a little"
rm -f magent/*.o stub/*.o UDP/UdpServerDir/*.o
strip magent/magent stub/stubd libnetmon/netmonup magent/UDP/UdpServerDir/UdpServer

echo "##### creating tarball $path from .."
tar czf $path -C .. $files
