#! /bin/sh
#
# Copyright (c) 2007 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

# waitexp - Wait for an experiment to be in the "active" state.
#    Required first two args are the project and experiment names.
#    Optional third arg is another state to wait for.

pid=$1
eid=$2
if [ -z "$pid" -o -z "$eid" ]; then
    echo "usage: $0 <pid> <eid> [<state>]"
    exit 1
fi
goal_state=$3
if [ -z $goal_state ]; then goal_state="active"; fi

max=600  # Max number of seconds to wait (10 minutes).
msg=60   # Give a message every so often (seconds)
sec=10   # Check every few seconds.
hdr=true

i=0; while [ $i -lt $(($max/$msg)) ]
do
    i=$(($i + 1))
    j=0; while [ $j -lt $(($msg/$sec)) ]
    do
	j=$(($j + 1))

	sql="select state from experiments where pid='$pid' and eid='$eid'"
	state=`echo "$sql" | mysql tbdb | tail +2`

	# Done if in the desired state now.
	if [ "$state" = "$goal_state" ]; then
	    echo ""
	    echo "$pid/$eid is $state."
	    echo ""
	    exit 0

	# Starting to wait.
	elif [ $hdr ]; then
	    echo ""
	    echo "*** $pid/$eid is $state.  Waiting for it to become $goal_state."
	    hdr=

	# Extra message if inactive but the state changes.
	elif [ "$ostate" != "$state" ]; then
	    echo "$pid/$eid $state"
	fi
	ostate=$state

	# Dots for progress between messages.
	echo -n .
	sleep $sec
    done

    # Show the inactive state.
    echo "$pid/$eid $state"
done

# Failed!
echo "*** Giving up waiting for $pid/$eid to become $goal_state. ***"
echo ""
exit 1
