#!/usr/bin/perl -w

#
# Copyright (c) 2009 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

#
# Make a simple top file - a bunch of PCs all in a big gigabit LAN
#

use strict;

die "Usage: $0 <nodes>\n" unless @ARGV == 1;

my ($nodes) = @ARGV;

print "node lannode lan\n";
for (my $i = 0; $i < $nodes; $i++) {
    print "node node$i pc\n";
    print "link vlink$i node$i lannode 1000 0 0 ethernet\n";
}
