#!/bin/sh

# Never run if systemd is running; it will do this.
[ -f /bin/systemctl ] && /bin/systemctl show-environment >/dev/null 2>&1 && exit 0

if [ -f /usr/local/etc/emulab/initscripts/tbprepare ]; then
    exec /usr/local/etc/emulab/initscripts/tbprepare stop
fi

exit 0
