#!/bin/sh
#
# Copyright (c) 2003-2014 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#
# Found on the internet, and customized for Emulab

#
# This script must run as root on ops, and should be run from cron daily, 
# with an entry in /etc/crontab (on ops) something like this:
# 
# 0   6   *   *   *   root   /usr/testbed/sbin/quotamail
#
# Some sites may wish to change the CC to a different list, or 
# possibly even remove it all together.
#
# Note that if FS_NODE != USERNODE, having a user check their quota won't
# work unless the rpc.rquotad(8) daemon is running on FS_NODE.  Our fs node
# installation script/directions should take care of this now.
#

PROJSTR="Project directory:    /proj"
GROUPSSTR="Group directory:      /groups"
USERSSTR="User/Home directory:  /users"
if [ -n "" ]; then
    SCRATCHSTR="Project scratch directory: "
else
    SCRATCHSTR=""
fi

MAINSITE=0
if [ $MAINSITE -ne 0 ]; then
    QUOTAHELP="See https://wiki.emulab.net/wikidocs/wiki/kb81 for more info on quotas."
else
    QUOTAHELP=""
fi

for i in `/usr/sbin/repquota -v  | awk '$2 ~ /\+/ {print $1}'`
do
(
# feel free to change this message!!!
cat << MESSAGE
From: Testbed Operations <testbed-ops@ops.cloudlab.umass.edu>
To: $i@cloudlab.umass.edu
Bcc: testbed-automail@ops.cloudlab.umass.edu
Subject: over disk quota at UMASS

Hello,

It looks like your disk usage has exceeded your disk quota. Please move or
remove some files to get below your quota. Disk space is limited, so if
you could clean up your directory it would be appreciated.

You can check your usage with the 'quota' command on ops.cloudlab.umass.edu:

ops.cloudlab.umass.edu> quota -v -l
`quota -v -l $i`

(Note: This will not work from nodes in an experiment.)

The directory trees (on ops.cloudlab.umass.edu) where you most likely have files are:

$PROJSTR
$GROUPSSTR
$USERSSTR
$SCRATCHSTR

PLEASE NOTE: just login to ops.cloudlab.umass.edu directly to do the cleanup!
You will not be able to swapin an experiment to access these directories
while over quota.

$QUOTAHELP

Thanks,
UMASS Testbed Operations
testbed-ops@ops.cloudlab.umass.edu

MESSAGE
) | /usr/sbin/sendmail -i -t
done

