#!/bin/sh

# Never run if systemd is running; it will do this.
[ -f /bin/systemctl ] && /bin/systemctl show-environment >/dev/null 2>&1 && exit 0

. /etc/default/rsyslog

exec /usr/sbin/rsyslogd -n $RSYSLOGD_OPTIONS
