#!/usr/bin/perl
#
# Copyright (c) 2009 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

use strict;
use warnings;

our ($START);
require "/users/mshobana/CloudLabonESI/emulab-devel-new/emulab-devel/sample_build/etc/node_usage.conf";

chdir "/users/mshobana/CloudLabonESI/emulab-devel-new/emulab-devel/sample_build/data/node_usage";

open F, "node_usage.raw" or die;

my @hunt_for;

if (@ARGV == 0 || @ARGV % 2 != 0) {
    print "Usage: $0 <pc1> <num1> [<pc2> <num2> ...]\n";
    exit 1;
}

while (@ARGV) {
    push @hunt_for, [shift @ARGV, shift @ARGV];
}

while (<F>) {
    chop;
    s/^(\d+) (\d+) // or die;
    my $time = $2;
    my %d;
    while (s/^ ([\w\d\-\?]+): (\d+) (\d+) (\d+) //) {
	$d{$1} = [$2, $3, $4];
    }

    my $num_satisfied = 0;
    foreach my $e (@hunt_for) {
	$num_satisfied++ if defined $d{$e->[0]} && ($d{$e->[0]}[0]) == $e->[1];
    }
    if ($num_satisfied == @hunt_for) {
	print "$time\n";
	exit 0;
    }
}

print STDERR "No sutable date found.\n";
exit 2;













