#!/usr/bin/perl -wT
#
# Copyright (c) 2003 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#
use English;

#
# Report that start command for this node is done. Report status.
#
sub usage()
{
    print "Usage: startcmddone <status>\n";
    exit(1);
}
my $stat;

# Drag in path stuff so we can find emulab stuff.
BEGIN { require "/etc/emulab/paths.pm"; import emulabpaths; }

#
# Load the OS independent support library. It will load the OS dependent
# library and initialize itself. 
# 
use libsetup;

usage()
    if (@ARGV != 1);
$stat = $ARGV[0];

# Sanity Check
if ($stat =~ /^(\d*)$/) {
    $stat = $1;
}
else {
    print "*** $0:\n" .
	  "    WARNING: Invalid exit status $stat. Reporting default.\n";
    $stat = 666;
}

#
# Then invoke the bootsetup routine in the library. All the work happens
# in there. 
#
startcmdstatus($stat);

exit 0;
