# -*- tcl -*-
#
# Copyright (c) 2000-2003 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

######################################################################
# vtype.tcl
#
# This defines the Vtype class.  Unlike other classes, Vtypes are 
# testbed specific.  They are generated by the tb-make-*-vtype 
# command.  A Vtype contains a list of types.  Nodes can also have
# Vtypes as their types.  Finally, a Vtype has a weight.
######################################################################

Class Vtype

Vtype instproc init {w t} {
    $self set types $t
    $self set weight $w
}

Vtype instproc updatedb {DB} {
    var_import ::GLOBALS::pid
    var_import ::GLOBALS::eid
    $self instvar name
    $self instvar types
    $self instvar weight

    spitxml_data "virt_vtypes" [list "name" "weight" "members" ] [list $self $weight $types ]
}

