#!/usr/bin/perl -w

#
# Copyright (c) 2000-2017 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#
use strict;

#
# schemacheck - Make sure that the scehma in the currently-running database
# matches the one in the checked-out source. Exits with value 1 if the two
# differ, 0 if they do not, and -1 if some error (such as the mysql server is
# not running, or the database does not exist) prevents us from telling if
# they differ or not
#

#
# Function prototypes
#
sub fatal(@);

#
# Configure variables
#
my $testbed_srcdir = "../..";
my $DBNAME         = "tbdb";

my $master_schema = "$testbed_srcdir/sql/database-create.sql";
my $schemadiff = "$testbed_srcdir/utils/schemadiff";
my $extraopts  = "";

my $mysqlvers = `mysql -V`;
if ($mysqlvers =~ /Distrib (\d\.\d)/) {
    my $vers = $1 + 0.0;
    if ($vers >= 5.0) {
	$extraopts .= "--skip-quote-names ";
    }
    if ($vers >= 5.7) {
	$extraopts .= "--set-gtid-purged=off ";
    }
}
else {
    fatal("Could not determine mysql version");
}

#
# XXX: Requires that mysqldump be in caller's $PATH - probably an OK
# assumption, but maybe not always
#
my $mysqldump = "mysqldump -d $extraopts $DBNAME";

#
# Make sure we can write the temporary file
#
my $db_schema = "/tmp/schemacheck.$$";
open(SCHEMAFILE,">$db_schema") or
    fatal("Unable to write to temporary file $db_schema: $!\n");
close(SCHEMAFILE);

#
# Stick the output of mysqldump into a file
#
system "$mysqldump 2> /dev/null > $db_schema";

#
# ... and compare it to the schema from the source
#
my $diff = (system("$schemadiff $db_schema $master_schema") >> 8);
unlink($db_schema);

if ($diff) {
    print "*** Your DB schema are out of date with $master_schema\n";
    print "    As a safety measure, you will not be able to install until\n";
    print "    this is resolved.\n";
    exit(1);
} else {
    exit(0);
}

sub fatal(@) {

    # Offset the text with a few blank lines, so it doesn't get lost in the
    # make messages
    warn "\n\n";
    warn "*** schemacheck - Unable to check database schema:\n";
    warn @_;
    warn "\n\n";

    exit(-1);

}
