#!/usr/bin/perl -w

#
# Copyright (c) 2000-2017 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#

#
# avail - prints a list of all available nodes
#

#
# Configure variables
#
use lib '/users/mshobana/CloudLabonESI/emulab-devel-new/emulab-devel/sample_build/lib';
use libdb;

my $d = 0; #debug mode

if ($#ARGV >= 0 && $ARGV[0] =~ /^-?h/i ) { 
  die("Usage:\navail [help] [type[=<type>]] [OS[=<OS>]] [ver[=<OS_ver>]]\n".
      "              [[includevirt] or [virtonly[=<phys>]]] [rand]\n".
      "              [limit=N] [aslist] [notprereserved]\n".
      "\n".
      "type \t= pc | shark\n"."OS \t= Linux | FreeBSD | NetBSD | ...\n".
      "ver \t= 6.2 | 3.4 | 4.0 | 5.2 | ...\n".#"deltas \t= anetd | ...\n".
      "includevirt: Include virtual nodes\n".
      "rand: Randomize result order\n".
      "limit: Limit count to N nodes\n".
      "A field name alone will show that field in the display of available\n".
      "nodes. A field name with '=' followed by a string will match nodes\n".
      "that have that string in that field.\n"
     );
}

print "Got ARGS = ",join(" ",@ARGV),"\n" if $d;

my %args = ();
while ($#ARGV >= 0) {
  $_ = shift;
  if ( ! /=/ ) { $args{"\L$_"}='='; } else {
    @_ = split('=',$_);
    my ($opt,$val) = @_ if ($#_ >= 0);
    if (!defined($val)) { $val=""; }
    $args{"\L$opt"}=$val if (defined($opt));
  }
}
if ( $d ) {
  print "Parsed args to:\n";
  foreach my $opt (keys %args) {
    print "$opt:\t$args{$opt}\n";
  }
}

my $join= "nodes as a left join reserved as b on a.node_id=b.node_id".
  " left join node_types as nt on a.type=nt.type";
my $cols= "a.node_id,a.type,nt.class";
my $cond= "b.node_id is null ";

if ($args{"virtonly"}) {
    $cond .= " and ( a.role='virtnode' ";

    if ($args{"virtonly"} ne '=') {
	$cond .= " and a.phys_nodeid='" . $args{"virtonly"} . "' ";
    }
    $cond .= " ) ";
}
else {
    $cond .= " and ( a.role='testnode' ";

    if ($args{"includevirt"}) {
	$cond .= " or a.role='virtnode' ";
    }
    $cond .= " ) ";
}

if ($args{"rand"}) {
    $order  = "rand()";
} else {
    $order = "priority";
}

if ($args{"limit"}) {
    $limit = "limit " . $args{"limit"};
} else {
    $limit = "";
}

my $os = 0;
my $delta = 0;

if (defined($args{"type"})) {
  # Make it a like, so if they type 'pc' they get pc850 and pc600...
  $cond .= " and (a.type='".$args{"type"}."' or nt.class='".$args{"type"}."')" 
    if $args{"type"} ne '=';
}
if (defined($args{"os"})) { 
  $os = 1;
  $cols .= ",d.OS";
  $cond .= " and d.OS='".$args{"os"}."'" if $args{"os"} ne '='; 
}
if (defined($args{"ver"})) { 
  $os = 1;
  $cols .= ",d.version";
  $cond .= " and d.version='".$args{"ver"}."'" if $args{"ver"} ne '='; 
}
if ($os) {
  $join .= " left join `partitions` as c on a.node_id=c.node_id";
  $join .= " left join os_info as d on c.osid=d.osid";
}
if (defined($args{"prereserve"})) {
    $pid = $args{"prereserve"};
    $cond .= " and a.reserved_pid='$pid' ";
}

if (defined($args{"notprereserved"})) {
    $cond .= " and a.reserved_pid is null";
}

my $cmd = "select $cols from $join where $cond order by $order $limit";

print "Sending cmd:\n$cmd\n" if $d;

my $result = DBQueryFatal($cmd);

if ($args{"aslist"}) {
    while (my ($node_id) = $result->fetchrow_array()) {
	print "$node_id\n";
    }
}
else { 
    print $result->as_string();
}

# Hacky. Batch daemon depends on this exit code.
exit($result->numrows);
