#!/usr/bin/perl
#
# Copyright (c) 2009 University of Utah and the Flux Group.
# 
# {{{EMULAB-LICENSE
# 
# This file is part of the Emulab network testbed software.
# 
# This file is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This file is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.
# 
# }}}
#
BEGIN {
  #add localcpan path to library search path
  if (-f glob("~/lib/perl5/Test/Harness.pm")) {
    my $localcpan_path = glob('~/lib/perl5');
    my $p5l = $ENV{PERL5LIB};
    unless ( (defined $p5l) && ($p5l =~ /$localcpan_path/)) {
      my $sep = (defined $p5l) ? ":" : "";
      $ENV { PERL5LIB} .= "$sep" . " $localcpan_path";
      push @INC, $localcpan_path;
    }
    push @INC, $localcpan_path;
  }
  $ENV{PERL5LIB} .= ":tests";
}

use lib qw(lib tests);
use SemiModern::Perl;
use Data::Dumper;
use TBConfig;
use TestBed::Harness;

my $testfile = shift @ARGV;
runharness($testfile);
