#!/bin/sh

# Never run if systemd is running; it will do this.
[ -f /bin/systemctl ] && /bin/systemctl show-environment >/dev/null 2>&1 \
    && (sv down pubsubd ; exit 0)

if [ -f /etc/init.d/pubsubd ]; then
    exec /etc/init.d/pubsubd stop
else
    sv down pubsubd
fi

exit 0
